[extend]
# Extend default GitLeaks rules
useDefault = true

[[rules]]
id = "audi-credentials"
description = "Audi connector credentials"
regex = '''(?i)(username|password|spin)["'\s]*[:=]\s*["']([^"'\s]+)'''
tags = ["audi", "credentials"]

[[rules]]
id = "mqtt-broker"
description = "MQTT broker configuration"
regex = '''(?i)broker["'\s]*[:=]\s*["']([^"'\s]+)'''
tags = ["mqtt", "config"]

[[rules]]
id = "secret-key"
description = "Application secret keys"
regex = '''(?i)SECRET_KEY["'\s]*[:=]\s*["']([a-f0-9]{32,})'''
tags = ["secret", "key"]

# Allowlist for known safe patterns
[allowlist]
description = "Global allowlist"
regexes = [
  '''test@test\.de''',  # Example emails in documentation
  '''testpassword''',   # Example passwords in documentation
  '''localhost''',      # Local development
  '''127\.0\.0\.1''',   # Local development
]

paths = [
  '''.*_test\.py''',     # Test files
  '''.*test.*\.py''',    # Test files
  '''.*/tests/.*''',     # Test directories
  '''.*/doc/.*''',       # Documentation
  '''README\.md''',      # Documentation
]
